from ..mixin import CpptrajMixin
from ..__version__ import get_version


class Rmsd(CpptrajMixin):

    template = f"# Generated by fmojinja version {get_version()}" + """ 
parm {{ parm }}
{%- for path in trajin %}
trajin {{ path }} 1 last {{ offset }}{% endfor %}
{{ "reference {}".format(reference) if reference else "" }}
autoimage anchor {{ anchor }} origin
align {{ align_mask }} {{ "move {}".format(mask) if mask else "" }} {{ "ref {}".format(reference) if reference else "first" }}
rmsd rmsd_align{{ align_mask }} {{ align_mask }} out {{ output }} nofit {{ "reference" if reference else "first" }}
{% if mask_list != None %}{% for m in mask_list %}rmsd rmsd_{{m}} {{ m }} out {{ output }} nofit {{ "reference" if reference else "first" }}
{% endfor %}{% else %}rmsd {{ mask if mask else "" }} out {{ output }} nofit {{ "reference" if reference else "first" }}{% endif %}
run
"""

    @classmethod
    def set_arguments(cls, p):
        p.add_argument("--offset", default=1)
        p.add_argument("-ml", "--mask-list", nargs="*")
        p.add_argument("-o", "--output", default="output.dat")
        return super(cls, cls).set_arguments(p)
