from ..mixin import CpptrajMixin
from ..__version__ import get_version


class Snapshot(CpptrajMixin):

    template = f"# Generated by fmojinja version {get_version()}" + """ 
parm {{ parm }}
{%- for path in trajin %}
trajin {{ path }} lastframe {% endfor %}
autoimage anchor {{ anchor }} origin
align {{ align_mask }} {{ "move {}".format(mask) if mask else "" }} {{ "ref {}".format(reference) if reference else "first" }}
{% for path in trajin %}
{% if mask != None %}reference {{ path }} lastframe
strip !({{ mask }}) 
parmwrite out {{ prefix ~ path.stem }}.parm
outtraj {{ prefix ~ path.stem  }}.pdb trajout onlyframes {{ loop.index }} nobox pdbter topresnum 
trajout {{ prefix ~ path.stem  }}.rst onlyframes {{ loop.index }}
unstrip
{%- else %}outtraj {{ prefix ~ path.stem  }}.pdb trajout onlyframes {{ loop.index }} nobox pdbter topresnum 
trajout {{ prefix ~ path.stem  }}.rst onlyframes {{ loop.index }}{% endif %}{% endfor %}

run
"""

    @classmethod
    def set_arguments(cls, p):
        p.add_argument("--prefix", default="snapshots/")
        return super(cls, cls).set_arguments(p)
