from unittest import TestCase
from test.support import captured_stdout
from fmojinja.cpptraj.hbond import Hbond
from fmojinja.__version__ import get_version
from pathlib import Path


class TestHbond(TestCase):
    test = Hbond()

    def test_simple_1(self):
        """
        simple test 1 for Hbond
        i.e. python -m fmojinja.cpptraj hbond -p test.prm -y test.crd --prefix hbond/
        :return: None
        """
        lines = self.test.render(
            trajin=[Path("test.crd")],
            parm=Path("test.prm"),
            prefix="hbond/",
        ).splitlines()
        self.assertEqual(lines[0], f"# Generated by fmojinja version {get_version()}")
        self.assertEqual(lines[1].split(), ["parm", "test.prm"])
        self.assertEqual(lines[2].split(), ["trajin", "test.crd", "1", "last"])
        self.assertEqual(lines[3].split(), ["hbond", "BB", "avgout", "hbond/test.dat"])
