from ..mixin import SubCommandMixin
from ..__version__ import get_version


class OptH(SubCommandMixin):

    template = f"# Generated by fmojinja version {get_version()}" + """ 
OptH
&cntrl
  imin=1, 
  maxcyc=100000, 
  ncyc=3000, 
  drms=0.1,
  ntr=1, 
  restraint_wt=10000, 
  restraintmask='!@H=',
  ig=-1,
  vlimit=-1,
  iwrap=1,
/

"""

    @classmethod
    def set_arguments(cls, p):
        p.add_argument("--hoge")
        return super(cls, cls).set_arguments(p)
