from ..mixin import TemplateRendererMixin
from ..__version__ import get_version


class OptH(TemplateRendererMixin):
    """
    e.g. python -m fmojinja.sander opth > $*.in; sander -O -i $*.in -o $*.mdout -r $*.rst_opt -p $*.parm -c $< -ref $<
    """

    template = f"# Generated by fmojinja version {get_version()}" + """ 
OptH
&cntrl
  imin=1, 
  maxcyc={{ maxcyc }}, 
  ncyc=3000,
  drms={{ drms }},
  ntr=1,
  restraintmask='!@H=',
  restraint_wt={{ restraint_wt }},
  ig={{ seed }}
/

"""

    @classmethod
    def set_arguments(cls, p):
        p.add_argument("-mc", "--maxcyc", default=10000)
        p.add_argument("--drms", default=1e-4)
        p.add_argument("-rw", "--restraint-wt", default=1000)
        p.add_argument("-ig", "--seed", default=-1)

        return super().set_arguments(p)
